// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBsOhJJ2DatQElyxa_sExi6-B7gPxU7foE',
    appId: '1:888289282299:web:e18336e61849d6c376485e',
    messagingSenderId: '888289282299',
    projectId: 'tiktok-jin-clone',
    authDomain: 'tiktok-jin-clone.firebaseapp.com',
    storageBucket: 'tiktok-jin-clone.appspot.com',
    measurementId: 'G-6LJ9LKV3MM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBIWuljkEC-TfVKbv3Q64vx2ElG4wGqo4w',
    appId: '1:888289282299:android:4359f1e2778b08c376485e',
    messagingSenderId: '888289282299',
    projectId: 'tiktok-jin-clone',
    storageBucket: 'tiktok-jin-clone.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDnkBDraWodZ03mRCMjfDJGTrPalpeER0U',
    appId: '1:888289282299:ios:a297e177b0b9d99776485e',
    messagingSenderId: '888289282299',
    projectId: 'tiktok-jin-clone',
    storageBucket: 'tiktok-jin-clone.appspot.com',
    iosClientId: '888289282299-3jmccddarr7k3amg83le74j8dbabckdf.apps.googleusercontent.com',
    iosBundleId: 'com.example.tiktokClone',
  );
}
